### ISSUE TITLE
Under the new Ubuntu 18.04, /etc/dbus-1/session.conf no longer exists

### ISSUE THREAD

**Issue by arjvik** [QMonkey/wsl-tutorial#3]
Hi,
I installed the new Ubuntu 18.04 from the Windows Store today. WSL works fine for me, and I followed your tutorial until it got to the point where I needed to edit `dbus` config. However, I can not find `/etc/dbus-1/session.conf`. There are instead two directories: `session.d`, which is empty, and `system.d`, which has a bunch of unrelated files. Performing a `cat * | grep -i listen` and `cat * | grep -i auth` turned up nothing. My graphical setup still works well, I can still run gedit and xeyes, but I keep getting complaints about dbus and connection refused. Any help appreciated.

Thanks,
Arjun

**Comment by dnapierata** [comment]
This is now located at `/usr/share/dbus-1/session.conf`

**Comment by arjvik** [comment]
thank you so much!

**Comment by monkeyplays23** [comment]
I would like to fix this on my WSL too can you give me directions the steps to fix so that it looks in /usr/share/dbus-1/session.conf instead of /var/run/dbus/system_bus_socket:

I get this error when trying to run kde desktop with vcxserv

```
$ sudo dpkg-reconfigure sddm
invoke-rc.d: could not determine current runlevel
 * Reloading system message bus config...                                                                              
Failed to open connection to "system" message bus: Failed to 
connect to socket /var/run/dbus/system_bus_socket: No such file or directory
invoke-rc.d: initscript dbus, action "reload" failed.
```

**Comment by muhammadsalmanafzal** [comment]
@monkeyplays23 you can try [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=444668]
It solved for me.

**Comment by m-salman-afzal** [comment]
@monkeyplays23 you can try https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=444668
It solved for me.
